server:
  port: 80

debug: false

spring:
  application:
    name: consumer-dept-80

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: consumer-dept80
    prefer-ip-address: true     #访问路径可以显示IP地址

# 配置Eureka的信息显示
info:
  app.name: springcloudconsumerdept80
  author: yangfang
  company.name: com.yangfang.springcloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$
